### ISSUE TITLE
Melhorias na Contribuição de Conteúdo: Utilizar Markdown no Repositório vs. Wiki

### ISSUE THREAD

**Issue by AlissonSteffens** [leonelsanchesdasilva/portugol-padroes#2]
Olá, sou o Alisson, participei do desenvolvimento do Portugol Studio (saí do projeto fazem uns 3 ou 4 anos, acredito que atualmente ele esteja estagnado, mas trabalhei nele durante um tempo com pesquisa e desenvolvimento). Acredito que tenho conteúdos de pesquisas nossas sobre a linguagem e estrutura, que posssam contribuir com o projeto, mas encontrei algumas dificuldades ao tentar fazer isso por meio da Wiki do GitHub. Por esse motivo, gostaria de sugerir uma mudança no modelo atual de organização do projeto, de forma a facilitar a contribuição de novos colaboradores.

Atualmente, o projeto utiliza a Wiki do GitHub como um agregador de conteúdo. No entanto, essa abordagem apresenta algumas dificuldades para novos contribuidores. Proponho a discussão sobre a utilização do próprio repositório Git para armazenar e gerenciar conteúdo em Markdown, com a possibilidade de renderizar as páginas utilizando GitHub Pages.

#### Pontos Positivos:
- Fácil de Navegar: Interface intuitiva para visualização e navegação dos conteúdos.
- Edição Rápida: Permite edições rápidas diretamente pelo navegador.

#### Pontos Negativos:
- Dificuldade para Contribuir.
- Controle de Versão Limitado: Menor visibilidade sobre o histórico de mudanças e dificuldade em gerenciar conflitos de edição.
- Reutilização de Conteúdo: Dificuldade em reutilizar o conteúdo da Wiki fora do ambiente do GitHub.

#### Pontos Positivos:
- Facilidade de Contribuição: Contribuidores podem utilizar ferramentas conhecidas e preferidas, como editores de texto locais, para criar e editar arquivos Markdown.
- Controle de Versão Completo: Todo o histórico de mudanças fica registrado no Git, com todas as vantagens de gerenciamento de versão.
- Flexibilidade e Portabilidade: Conteúdo em Markdown é fácil de reutilizar e portar para outros ambientes.
- Integração com GitHub Pages: Possibilidade de configurar um template e renderizar as páginas de forma bonita e organizada utilizando GitHub Pages.

#### Pontos Negativos:
- Configuração Inicial: Pode exigir um esforço inicial maior para configurar o ambiente e templates para GitHub Pages.
- Complexidade de Navegação: Sem uma interface dedicada como a Wiki, a navegação pode ser menos intuitiva para usuários que acessam diretamente pelo repositório.

### Estrutura de Pastas:
Criar uma pasta docs na raiz do repositório para armazenar os arquivos Markdown.
Organizar o conteúdo em subpastas conforme necessário para manter uma estrutura lógica e limpa.

### Template para GitHub Pages:
Utilizar Jekyll ou outro gerador de sites estáticos compatível com GitHub Pages.
Configurar um template que permita fácil navegação e busca do conteúdo.

### Documentação e Guias de Contribuição:
Fornecer um guia detalhado sobre como contribuir com conteúdo, incluindo exemplos de formatação em Markdown e instruções.

**Comment by leonelsanchesdasilva** [comment]
Oi, @AlissonSteffens 👋 

Obrigado pelo interesse nesse projeto. De fato eu não desenvolvi muito a estrutura aqui, até porque isso é mais como um bloco de notas público do que um projeto mais sofisticado, mas eu adoro a ideia de transformar num projeto Jekyll!

Você gostaria de me ajudar com uma estrutura inicial? Se sim, só me mandar uma PR com a ideia completa. Caso contrário, eu posso elaborar algo.
